---
- hosts: logstash_kibana
  tasks:

  - include_role:
      name: elk-elasticsearch-6.3.2

  - include_role:
      name:  elk-logstash-6.3.2

  - include_role:
      name: elk-kibana-6.3.2

  - include_role:
      name: elk-index-patterns
      
  - include_role:
      name: elk-vis-status-table

  - include_role:
      name: elk-vis-jboss-all

  - include_role:
      name: elk-vis-jboss-error

  - include_role:
      name: elk-vis-jboss-severe

  - include_role:
      name: elk-vis-jboss-warn
      
  - include_role:
      name: elk-dash-status-table

  - include_role:
      name: elk-dash-jboss

#- name: Create index patterns
#  hosts: localhost
#  tasks:
#
#  - name: "Create index patterns"
#    uri:
#      url: http://{{ kibana_host }}:{{ kibana_port }}/api/saved_objects/index-pattern/{{ item }}
#      method: POST
#      body: { "attributes": {"title": "{{ item }}" }}
#      body_format: json
#      headers:
#        kbn-xsrf: kibana
#    loop:
#      - metricbeat-*
#      - filebeat-*
#      - heartbeat-*
#
#  - name: "Set default index pattern"
#    uri:
#      url: http://{{ kibana_host }}:{{ kibana_port }}/api/kibana/settings
#      method: POST
#      body: { "changes": { "defaultIndex": "metricbeat-*" } }
#      body_format: json
#      headers:
#        kbn-xsrf: kibana

#curl -POST "http://aws-a-log1:5601/api/kibana/settings" -H "Content-Type: application/json" -H "kbn-xsrf: true" -d '{"changes": { "defaultIndex": "filebeat-*"}}'

#curl -X GET "http://mtc2-sysmon:5601/api/saved_objects/dashboard/b0d82da0-8e0c-11e9-a7bd-1b8a2a5c37fd" -H 'kbn-xsrf: true'

  

#curl -X GET "http://mtc2-sysmon:5601/api/saved_objects/dashboard/b0d82da0-8e0c-11e9-a7bd-1b8a2a5c37fd" -H 'kbn-xsrf: true'
